FROM node:20-alpine

RUN npm install -g parse-dashboard@latest

COPY parse-dashboard-config.json /parse-dashboard-config.json

EXPOSE 4040

CMD ["parse-dashboard", "--config", "/parse-dashboard-config.json", "--allowInsecureHTTP", "true"]
