version: '3'

services:
  parse-server:
    build: 
      context: .
      dockerfile: Dockerfile-parse
    environment:
      PARSE_SERVER_APPLICATION_ID: ${PARSE_APP_ID}
      PARSE_SERVER_MASTER_KEY: ${PARSE_MASTER_KEY}
      PARSE_SERVER_DATABASE_URI: ${PARSE_SERVER_DATABASE_URI}
      PARSE_SERVER_URL: http://parse-server:1337/parse
      PARSE_SERVER_HOST: 0.0.0.0
      PARSE_PUBLIC_SERVER_URL: ${PARSE_PUBLIC_SERVER_URL}
      PARSE_SERVER_CLOUD: /parse-server/cloud/main.js
      PARSE_SERVER_MOUNT_PATH: "/parse"
      MINIO_BUCKET_NAME: ${MINIO_BUCKET_NAME}
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      REDIS_URL: redis://redis:6379
      S3_BUCKET: ${MINIO_BUCKET_NAME}
    ports:
      - "1337:1337"
    depends_on:
      - redis
      - minio


  parse-dashboard:
    build:
      context: .
      dockerfile: Dockerfile-dashboard
    environment:
      - PARSE_DASHBOARD_SERVER_URL=http://parse-server:1337/parse
      - PARSE_DASHBOARD_MASTER_KEY=${PARSE_MASTER_KEY}
      - PARSE_DASHBOARD_APP_ID=${PARSE_APP_ID}
      - PARSE_DASHBOARD_APP_NAME=MyApp
      - PARSE_DASHBOARD_USER_ID=${PARSE_DASHBOARD_USER_ID}
      - PARSE_DASHBOARD_USER_PASSWORD=${PARSE_DASHBOARD_USER_PASSWORD}
      - PARSE_DASHBOARD_ALLOW_INSECURE_HTTP=true


  n8n:
    image: n8nio/n8n:latest
    environment:
      - N8N_HOST=n8n.${DOMAIN_NAME}
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - N8N_USER_MANAGEMENT_DISABLED=true
      - WEBHOOK_URL=http://n8n.${DOMAIN_NAME}/
      - GENERIC_TIMEZONE=UTC
      - N8N_ENCRYPTION_KEY=${N8N_ENCRYPTION_KEY}
      - NODE_ENV=development
      - N8N_DIAGNOSTICS_ENABLED=false
      - N8N_SECURE_COOKIE=false


  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001" --address ":9000"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_BROWSER_REDIRECT_URL: http://miniodash.${DOMAIN_NAME}
    volumes:
      - minio_data:/data


  mongo:
    image: mongo:latest
    networks:
      - internal

  redis:
    image: redis:alpine
    networks:
      - internal

  dozzle:
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  minio_data:
  mongo_data:
  redis_data:

networks:
  web:
    external: true
  internal:
    name: ${COMPOSE_PROJECT_NAME:-parse}_internal
